"""Add pos_order_id to sales_invoices

Revision ID: b1ab24d9e06d
Revises: d2add373c12c
Create Date: 2026-01-15 03:52:05.567404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ab24d9e06d'
down_revision = 'd2add373c12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_invoices_pos_order_id', 'pos_orders', ['pos_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_invoices_pos_order_id', type_='foreignkey')
        batch_op.drop_column('pos_order_id')

    # ### end Alembic commands ###
