"""Remove unique constraint from barcode and sku fields

Revision ID: 7da640fe5dae
Revises: fe0d67f122a6
Create Date: 2026-01-11 02:42:19.798596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da640fe5dae'
down_revision = 'fe0d67f122a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=1)

    # ### end Alembic commands ###
