"""Add accounting settings table

Revision ID: fe0d67f122a6
Revises: 
Create Date: 2026-01-11 02:27:11.888853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0d67f122a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=64), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('accounting_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_revenue_account_id', sa.Integer(), nullable=True),
    sa.Column('sales_tax_account_id', sa.Integer(), nullable=True),
    sa.Column('sales_discount_account_id', sa.Integer(), nullable=True),
    sa.Column('accounts_receivable_account_id', sa.Integer(), nullable=True),
    sa.Column('sales_cost_account_id', sa.Integer(), nullable=True),
    sa.Column('purchase_expense_account_id', sa.Integer(), nullable=True),
    sa.Column('purchase_tax_account_id', sa.Integer(), nullable=True),
    sa.Column('purchase_discount_account_id', sa.Integer(), nullable=True),
    sa.Column('accounts_payable_account_id', sa.Integer(), nullable=True),
    sa.Column('inventory_account_id', sa.Integer(), nullable=True),
    sa.Column('inventory_adjustment_account_id', sa.Integer(), nullable=True),
    sa.Column('cash_account_id', sa.Integer(), nullable=True),
    sa.Column('default_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('pos_cash_account_id', sa.Integer(), nullable=True),
    sa.Column('pos_card_account_id', sa.Integer(), nullable=True),
    sa.Column('auto_create_journal_entries', sa.Boolean(), nullable=True),
    sa.Column('auto_post_journal_entries', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accounts_payable_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['accounts_receivable_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cash_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['default_bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['inventory_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['inventory_adjustment_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['pos_card_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['pos_cash_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['purchase_discount_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['purchase_expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['purchase_tax_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sales_cost_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sales_discount_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sales_revenue_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sales_tax_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
